name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name : Shellcheck
        uses: sudo-bot/action-shellcheck@latest
        with:
          # https://github.com/koalaman/shellcheck#how-to-use
          cli-args: "-x mnm.sh"
      - name: Hundred line check
        run: '[ $(wc -l < mnm.sh) -eq 100 ] && exit 0 || exit 1'
