name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: apt update
      - run: apt install shellcheck
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Shellcheck
        run: shellcheck -x mnm.sh
      - name: Hundred line check
        run: '[ $(wc -l < mnm.sh) -eq 100 ] && exit 0 || exit 1'
